The dataset includes Images for 5 types of flowers . The task is to train the model which will be able to classify the flowers based on their images correctly.

The link for this dataset is - https://www.kaggle.com/alxmamaev/flowers-recognition

In [31]:
#define file paths.
import os
daisy_path = "../input/flowers/flowers/daisy/"
dandelion_path = "../input/flowers/flowers/dandelion/"
rose_path = "../input/flowers/flowers/rose/"
sunflower_path = "../input/flowers/flowers/sunflower/"
tulip_path = "../input/flowers/flowers/tulip/"


Reading in all the images using cv2 library in memory from their respective folders.

In [32]:
from os import listdir
import cv2
img_data = []
labels = []

size = 128,128
def iter_images(images,directory,size,label):
    try:
        for i in range(len(images)):
            img = cv2.imread(directory + images[i])
            img = cv2.resize(img,size)
            img_data.append(img)
            labels.append(label)
    except:
        pass

iter_images(listdir(daisy_path),daisy_path,size,0)
iter_images(listdir(dandelion_path),dandelion_path,size,1)
iter_images(listdir(rose_path),rose_path,size,2)
iter_images(listdir(sunflower_path),sunflower_path,size,3)
iter_images(listdir(tulip_path),tulip_path,size,4)

In [33]:
len(img_data),len(labels)

(3386, 3386)

Checking the data size, confirmining that images and labels are the same.

In [35]:
import numpy as np
data = np.asarray(img_data)
#div by 255
data = data.astype('float32') / 255.0
labels = np.asarray(labels)

Checking the shape of the input data channel.

In [36]:
data.shape,labels.shape

((3386, 128, 128, 3), (3386,))

In [37]:
from sklearn.model_selection import train_test_split
# Split the data
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, shuffle= True)

Creating a test and train split.

In [38]:
from keras.utils import to_categorical
classes = 5
y_train_binary = to_categorical(y_train,classes)
y_test_binary = to_categorical(y_test,classes)

Here I define the a sequential convolutional 2 dimensional model, which uses Keras and many hidden layers with relu activations.
We train the model for 10 epochs and perform validations on validation dataset.

In [39]:
from keras.models import Sequential
from keras.layers import Conv2D,MaxPool2D,Flatten,Dense

model = Sequential()
model.add(Conv2D(32, (3,3),input_shape=(128, 128, 3),activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(1000,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(5,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

batch_size = 128
epochs = 10
model.fit(x_train, y_train_binary,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test_binary))


Train on 2708 samples, validate on 678 samples
Epoch 1/10
2708/2708 [==============================] - 92s 34ms/step - loss: 2.2671 - acc: 0.2840 - val_loss: 1.3246 - val_acc: 0.3968
Epoch 2/10
2708/2708 [==============================] - 81s 30ms/step - loss: 1.2820 - acc: 0.4309 - val_loss: 1.3829 - val_acc: 0.3805
Epoch 3/10
2708/2708 [==============================] - 80s 30ms/step - loss: 1.1046 - acc: 0.5395 - val_loss: 1.1968 - val_acc: 0.5059
Epoch 4/10
2708/2708 [==============================] - 81s 30ms/step - loss: 1.0218 - acc: 0.5739 - val_loss: 1.1713 - val_acc: 0.5678
Epoch 5/10
2708/2708 [==============================] - 81s 30ms/step - loss: 0.8095 - acc: 0.6946 - val_loss: 1.2682 - val_acc: 0.5516
Epoch 6/10
2708/2708 [==============================] - 82s 30ms/step - loss: 0.6406 - acc: 0.7770 - val_loss: 1.1544 - val_acc: 0.6047
Epoch 7/10
2708/2708 [==============================] - 80s 30ms/step - loss: 0.4059 - acc: 0.8612 - val_loss: 1.3409 - val_acc: 0.5870
E

Import the confusion matrix and print the matrix of right and wrong predictions.

In [40]:
from sklearn.metrics import confusion_matrix
pred = model.predict_classes(x_test)
cm = confusion_matrix(y_test, pred)
print(cm)

[[108  11   5  19  17]
 [  9   5   0  10   0]
 [ 49   2  30  17  64]
 [  7   5   0 123  11]
 [ 21   3   9  26 127]]


Print the accuracy.

In [41]:
acc = (cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3]+cm[4][4])/(len(y_test))
print('Accuracy =',(acc*100),'%')

Accuracy = 57.9646017699115 %
